### PR TITLE
Added PUT method to 'deposit_into_pot' HTTP request

### PR DESCRIPTION
**Pull request by tjl694**
Previously this was not included, and so was assumed to be a GET request which resulted in an error and no money being added to a pot. With the PUT method added, money is now added to the pot and a success response is received as specified in the API docs

### CODE REVIEW

**Comment by tjl694** [comment]
It may be possible that other defs are in need of such edits as well

**Comment by Solije** [comment]
Hmm, that's a bit odd... This should be being handled automatically from within the `make_requests` method as we're attaching data to the request, and I'm a bit surprised that it isn't. I'll take a closer look soon.

**Comment by tjl694** [comment]
I noticed that the PUT is specified in other defs such as [line 256 of `withdraw_from_pot`](https://github.com/muyiwaolu/monzo-python/blob/38d50f6876856101ab638b7829859f1dfbff783d/monzo/monzo.py#L256) so thought it had just been missed

**Comment by marrold** [comment]
I experienced the same issue and applied the same fix

**Comment by Tuquar** [comment]
Hi,
When will this change make it's way to the next pip release? I am also having this problem but unfortunately the latest version is 0.9.0 which was released on 09 Feb, before this fix.

Thanks!

**Comment by muyiwaolu** [comment]
Yikes @Tuquar .... let me update pip now

**Comment by mattlennon3** [comment]
Much appreciated @muyiwaolu, thanks it works great :)

**Pull request merged**
