### PR TITLE
Added support for pagination in get_transactions

### PR DESCRIPTION
**Pull request by Solije**
This PR allows transactions to be be automatically filtered based on their date on Monzo's server.

### CODE REVIEW

**Comment by samdobson** [comment]
Nice. In terms of testing, I guess we would need to mock responses from the server? I find it strange that the API provides `limit`, but not `offset`. How are we to go about pagination? I guess use the last transaction id as `before` for the next page?

**Comment by Solije** [comment]
> Nice. In terms of testing, I guess we would need to mock responses from the server? 

I'm beginning to think this is going to be needed soon as well. The current tests don't sit that well with me at the minute and I'm planning on giving them some love.

>How are we to go about pagination? I guess use the last transaction id as `before` for the next page?

Yup, that seems to be the way to go about it. Although now you mention it, I should probably have a look at attaching an easy way to call the next page to the returned list of transactions.

**Comment by samdobson** [comment]
Great stuff.

(I just realised that transactions are returned from oldest to newest, so where I said `before` above it should actually be `since`)

**Comment by Solije** [comment]
The function to get the next page is now included in the response and can be evaluated as

```python3
nextpage = page['next_page']()
```

This is a bit ugly, I've done a little work on some subclasses of dict to improve the functionality of various responses so I'll probably make something like a TransactionList.nextpage() class and method in a different PR to hide this.

**Comment by samdobson** [comment]
Neat solution  - clever use of `partial`. Thanks also for the usage example - we should start collecting these for the docs (though let's wait for an update on #4 before starting).

**Comment by muyiwaolu** [comment]
@Solije @samdobson great work on this. I'm looking into updating a bunch of the pagination and tests in general too :)

**Comment by muyiwaolu** [comment]
@Solije I'm giving myself homework this weekend to add tests to this.

**Pull request closed without merging**
